SELECT TOP (1000) [Sub_ICB_Location_ODS_Code]
      ,[Sub_ICB_Location_Name]
      ,[Sub_ICB_Location_Name_Local_Reference]
      ,[Sub_ICB_Location_Non_Primary_Role]
      ,[ICB_Code]
      ,[Integrated_Care_Board_Name]
      ,[ICB_Non_Primary_Role]
      ,[Region_Code]
      ,[Region_Name]
      ,[UDALFileID]
  FROM [Internal_Reference].[Sub_ICBs_2022_23_1]
